### ISSUE TITLE
Silverjuke doesn't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by AnwarShah** [silverjuke/silverjuke#78]
I installed Ubuntu's 16.2.3 version and latest 16.5.3 version from  github repo. It doesn't start from GUI. And from terminal, it says

```
Fatal Error: We'll terminating Silverjuke now.
Sorry, there's nothing we can do.
Aborted
```

**Comment by r10s** [comment]
at least 17.10 seems to work again. can anyone else confirm this?
