### ISSUE TITLE
Silverjuke fails to build against upnp 1.8

### ISSUE THREAD

**Issue by toddy15** [silverjuke/silverjuke#81]
Hi,

I've received a [bug report in Debian](https://bugs.debian.org/884250), concerning the silverjuke package. It fails to build from source with upnp 1.8. The full build log is accessible here:

https://people.debian.org/~sramacher/logs/upnp/silverjuke_amd64-2017-12-12T20:51:39Z.log

**Comment by ukleinek** [comment]
Note the Debian bug report also contains a patch that makes it build with libupnp 1.6.24 and 1.8

**Comment by r10s** [comment]
@ukleinek thank you very much, i will check this these days, as soon as i find some time

**Comment by r10s** [comment]
thank you for the fix!

Silverjuke fails to build against libupnp 1.6; https://github.com/silverjuke/silverjuke/commit/6f46c39dc5998c5bb50936756c10b9b577f55710 fixes this (libupnp 1.6 is still in the current Ubuntu version, not sure if it is worth supporting it at all, however, i wanted to compile the stuff on my current machine :)

moreover, i'm amazed that the double define of 
```
static int client_event_handler(Upnp_EventType eventType, void* p_event, void* user_data)
```
and
```
static int client_event_handler(Upnp_EventType eventType, const void* p_event, void* user_data)
```
does not result in a compiler error - the only difference seems to be the `const` - however, maybe i've also overseen something, i'm a little bit slow by a flu these days ...

**Comment by ukleinek** [comment]
6f46c39 looks wrong. For one this is expected to break once these defines are provided by libupnp. `UpnpDiscovery_get_Location_cstr` is already defined in upstream, maybe it's time to prod @mrjimenez  to release 1.6.25 to get this into distributions. Furthermore the first define looks bogus.

Regarding the double define: For C this would indeed be a problem, but this is C++.

**Comment by ukleinek** [comment]
I just compiled silverjuke successfully with 6f46c39dc599 reverted on top of 10ec89d76904 with Debian's libupnp6_1.6.24-4 (which contains mrjimenez/pupnp@8177a4195a4d4a5d6cb095eaf4ca5b65ac446381 which is included in 1.6.23)

Also note that printing UPNP_VERSION_STRING gives the version string that silverjuke was linked against at compile time which might differ from the version in use during run time. So IMHO this might result in more confusion than good.

**Comment by r10s** [comment]
@ukleinek Thank you for the hint. I've done a little research:
- Ubuntu 16.04 uses libupnp-1.6.19 which does not add compat code
- checking some versions from the [upstream](https://sourceforge.net/projects/pupnp/files/pupnp/), I found out the the compat code is preset in libupnp-1.6.24 but not in libupnp-1.6.22 (not sure for libupnp-1.6.23, the archive is missing, maybe it does not exist)

so, i modified silverjuke compat code, see https://github.com/silverjuke/silverjuke/commit/16e0284c233df9629d1754ee585394428c4818f8

Can you please check if this is fine for you?

> Regarding the double define: For C this would indeed be a problem, but this is C++.

Of course, you're right. I have been done too much plain C the last time :)

**Comment by r10s** [comment]
Regarding the UPNP_VERSION_STRING: do you know a way to get the runtime version? I have the feeling that this might be useful in the log here and there ...

**Comment by ukleinek** [comment]
AFAIK there is no API-call to find the runtime version string. I wouldn't want to add new stuff to the v1.6 branch.

**Comment by r10s** [comment]
Okay, thank you for the information. Silverjuke is already checked in to Debian/Ubuntu, so I do not want to add new stuff here either. Maybe in the next release :)
