### ISSUE TITLE
license means? linux complete version or trial too?

### ISSUE THREAD

**Issue by mckaygerhard** [silverjuke/silverjuke#83]
Hi, i see the download page, noted that for linux there's no license key or something.. for privative OS the ready to install executables are trials.. 

it's just curious but what that means? linux are too a trial version? the complete version for linux?

can you clarify for me and many others that?

**Comment by r10s** [comment]
linux:
- for linux, there is no trial version, you get the full version without charge or any other strings but the gpl attached
- you can use the linux version for public or commercial use
- the full code is released under the gpl, so if you change anything, you have to release the changed code.
- the packaging for linux is done by ubuntu/debian/suse and so on, we do not offer binaries for these os here.

for windows and mac
- most of the code is released under the gpl
- we charge money for the binaries, depending on private/commercial use

hth :)

**Comment by mckaygerhard** [comment]
**I LIKE IT!** It seems very fair to me, that if a system is proprietary, it will be charged, and otherwise not will be charged, although any work implies an effort, here we are talking about the compilation service.

I'm really happy with the style of how you offer binaries, excellent that for windows you have to pay and for others no .. of course others do not come precompiled, since only the source is offered and one is the one that relays it.

Excellent.

**Comment by mckaygerhard** [comment]
i'll will cited your way of how to release a binaries.. thanks for clarification.. really great.

**Comment by r10s** [comment]
@mckaygerhard no problem, you're welcome.
