### ISSUE TITLE
How to create images for skins?

### ISSUE THREAD

**Issue by falreis** [silverjuke/silverjuke#88]
Hi everyone.
I'm struggling to create an image for a new skin.
Using random images, Silverjuke indicates that the image contains several subimages.
I don't know how to fix this situation. I'm using Gimp to edit my images but it not work. I created a border in some images, but it keeps informing a lot of subimages.
Is there a software to create images for skins?
Thanks a lot.

**Comment by r10s** [comment]
gimp is just fine.

some hints:

- one image consists of several subimages, divided by a 1pixel-boder in the color of the upper-left pixel
- so, random images won't work without adaption
- use png for images
- further docs: https://github.com/silverjuke/silverjuke/blob/master/docs/skinning.md#overview
- have a look at the examples, eg. https://github.com/silverjuke/silverjuke/tree/master/src/sjdata/skins/silveriness.sjs for the default skin

this is how an image of eg. the control buttons look like:

![z_ctrl](https://user-images.githubusercontent.com/9800740/68871819-5291c980-06fd-11ea-96e2-7feeeef671b1.png)

**Comment by falreis** [comment]
Thank you @r10s.
In my new layout I just needed a background image. Then it worked when I created a border with 2 pixels (not 1 pixel) around the whole image, following Nice1 skin.
Best regards.

**Comment by r10s** [comment]
you're welcome!
